### PR TITLE
Filter the list of available methods

### PR DESCRIPTION
**Pull request by przepompownia**
depending on the current context.

### CODE REVIEW

**Comment by przepompownia** [comment]
I spent quite a lot of time to trying on trying to filter non static method with the binary filter. Example from http://php.net/manual/en/reflectionmethod.getmodifiers.php suggests that 65536 works as such filter and I have confirmed it. But 16-th power of two is not the value of any explicitly defined ReflectionMethod constant associated with modifiers so I decided to not use this undocumented number. Trying to use its bit by negation of binary alternative of the rest of constants was not succeeded for me. 

Separate logic for checking public|protected|private was needed independently of the above problem. 

Similar work will be needed for filtering properties list.

**Comment by lvht** [comment]
@przepompownia Could you rebase the master branch? I am very sorry for making trouble.

And, would you @przepompownia like to join the phpvim organization to coding PHP under vim more better ? :)

**Comment by przepompownia** [comment]
No problem with joining to phpvim :)

**Comment by lvht** [comment]
@przepompownia I have sent you invitation. Please accept.

**Comment by przepompownia** [comment]
After fetching remote phpvim I got forced updated commits and I do not understand why did you make rebase some of them. I now have choice either to change my remote history or to merge but getting duplicated commits.

**Comment by lvht** [comment]
@przepompownia so sorry. Please use rebase. I just used rebase to remove the duplicated commits.

**Comment by lvht** [comment]
@przepompownia I will never rebase the master branch in the future. I promise.

**Comment by przepompownia** [comment]
My experience with this pull request show that I could safely merge commits (7c5ad28 was the example) even with those belongs to (not yet confirmed) pull request. History on the remote repositories has not been touched. In this case it was too late to make rebase containing only local commits. 

Probably no one is interested in tracking my repository at the moment, so I my once change history without making the problem to anyone, but let us not repeat this practice.

**Pull request merged**
