### PR TITLE
change default match type

### PR DESCRIPTION
**Pull request by lvht**

### CODE REVIEW

**Comment by lvht** [comment]
@przepompownia

**Comment by przepompownia** [comment]
While doing new functionalities I see that separation of config is increasingly needed, especially when we want to use different (but both possible to set by one parameter) behavior or we have to inject alternative implementation of the logger (for example non-existing yet NullLogger to disable logging when it not needed), class info repository or something else. 

Please see the `configuration` branch.

**Comment by lvht** [comment]
@przepompownia Is there any problem to make the `MATCH_HEAD` as default option?

**Comment by przepompownia** [comment]
No, I hope you accept https://github.com/phpvim/phpcd.vim/pull/38 where `HeadPatternMatcher` is set as default matcher.

**Pull request closed without merging**
