### PR TITLE
generate namespace and class name according psr4

### PR DESCRIPTION
**Pull request by lvht**
According PSR-4, the class's namespace is namespace prefix (defined in composer.json) plus file relative path, and the class's name is the file name. So, if we create a php file according the psr4, the namespace is also determined.

This PR give phpcd the ability to generate the psr4 namespace and class automatically. After type in the namespace or class, just type `C-x C-o` to generate the namespace and classname.

### CODE REVIEW

**Comment by lvht** [comment]
@imaben @przepompownia

**Comment by przepompownia** [comment]
It seems to work, but I would like to propose small refactor related to this
patch but not only. 

First, note that the $root variable is not defined explicitly and now it is in
both subclasses. It seems to be natural to move it and its setter up to
RPCServer. I have not found any external $root setting except right after
construction or directly in the constructor, so the $root variable may be set
as an parameter of the constructor.

**Comment by przepompownia** [comment]
The next motivation I got when I trying to testy your commit. Daemon did not work with the newly installed PHP7 from Debian repo. The cause was the lack of msgpack extension but i discovered it after running PHPID manually from bash. 

I would like to create simple logger class that gives the same effect, especially uses code form your methods, but exists as a separate responsibility. It would be instantiated in the "controller", use there and passed to RpcServer as another dependency and used there. It would be good to make it as an implementation of `\Psr\Log\LoggerInterface` (http://www.php-fig.org/psr/psr-3/).

**Comment by lvht** [comment]
Hello @przepompownia .  You idea is wonderful. However, I think the reflection work you made should be separated into a new PR, which will make this PR smaller and simpler.

**Comment by przepompownia** [comment]
If so, I propose to merge only the first my commit (fdcef57) into this PR. I do not know about another technical way to do this than resetting `psr4` branch to it. Order not to lose further commits I created a new branch `di`.

**Comment by przepompownia** [comment]
See 8781209. It revealed when I could not complete subnamespace from `autoload-dev`.

**Pull request merged**
