### PR TITLE
Standalone rpc

### PR DESCRIPTION
**Pull request by lvht**
- use the monolog
- use a standalone msgpack rpc impl

### CODE REVIEW

**Comment by lvht** [comment]
@przepompownia @imaben

**Comment by przepompownia** [comment]
Decoupling server responsibilities (i.e. forking or communication) is very good work and it will be good to merge it into master if it works. 

The existing Logger is primitive, but it works quite good (until we control the size of the log file ;) ). Its existence does not conflict with any other `Psr\Log\LoggerInterface` implementation so I propose to preserve it, not necessary as the default.

I will try to merge `standalone-rpc` to `complete_class_names`. Especially I would like to move the creation and configutarion of Monolog instance into createLogger() in Factory.

**Comment by przepompownia** [comment]
It seems that we abandon versioning of `composer.lock`.

**Comment by przepompownia** [comment]
Why not to do call index() inside PHPID constructor?

**Comment by przepompownia** [comment]
Please `use LoggerAwareTrait;`  as previously.

**Comment by przepompownia** [comment]
Why not to  use phpvim copy i.e.
```
-         "lvht/msgpack-rpc": "dev-master"
+         "phpvim/msgpack-rpc": "dev-master"
```
in composer.json?

**Comment by przepompownia** [comment]
I merged both branches into `complete_class_names+standalone-rpc`. Some first tests suggest that seems to work! 

Intentionally I decided to lost (for a while) the communication between parent and child process so reloading class info repository will not work at the running server.

**Comment by przepompownia** [comment]
Two days ago I made merge on an independent copy and tested on unchanged tree...
Now  the merge works correctly.

**Pull request merged**
